### PR TITLE
Generate Set instead of Type

### PR DESCRIPTION
**Pull request by clarus**

### CODE REVIEW

**Comment by anton-trunov** [comment]
@clarus Could you please comment on the purpose of this change. I'm asking just out of sheer curiosity :)
PS I also noticed that you switched to `-impredicative-set`

**Comment by clarus** [comment]
Hi,

This change is an experiment for now. We ran into some issues with "universe inconsistencies" while doing proofs on the generated Coq code for Tezos. I do not know where they come from in general and I am thinking it would be simpler to always use `Set` to prevent this kind of errors. In some cases however, like for example with existential variables:
```ocaml
type 'a foo =
  | Bar : 'b -> 'a foo (* existential variable 'b *)
```
Coq refuses the definition without impredicative sets:
```coq
Reserved Notation "'foo".

(* Error message : "Large non-propositional inductive types must be in Type." *)
Inductive foo_gadt : Set :=
| Bar : forall {b : Set}, b -> foo_gadt

where "'foo" := (fun (a : Set) => foo_gadt).

Definition foo := 'foo.
```
Thus we use the `-impredicative-set` option. To me this option is fine as sets were impredicative in the first versions of Coq and this is only incompatible with classical axioms. Maybe we should provide an option to `coq-of-ocaml` to choose between `Set` and `Type`. We will see how it goes for our proofs with `Set` and backtrack if needed.

**Comment by anton-trunov** [comment]
@clarus Thank you so much for the explanation! The `-impredicative-set` option totally makes sense here, but those universe inconsistencies are very surprising to me.

**Comment by clarus** [comment]
Np. Note that the universe inconsistencies only appeared while stating some conversion functions between the imported Coq code from Tezos and our formalization. The problem may lie in the way we convert things.

**Pull request merged**
