### PR TITLE
vendor merlin and 4.10

### PR DESCRIPTION
**Pull request by EduardoRFS**
## What this does

Switches to the same used version of merlin as ocaml-lsp, who also has the same requirement of depending on internals of merlin, but is kept updated. If this isn't desirable I can remove it

It also bumps the current version to OCaml 4.10, dropping support to 4.9, if 4.9 is required I can use cppo to support both versions

### CODE REVIEW

**Comment by clarus** [comment]
Hi,

Thanks for the work! I did not know about the ocaml-lsp project and the use of sub-modules for Merlin.

Unfortunately, I also needed to make some changes to Merlin in order to run coq-of-ocaml. For example, when I run the tests I get:
```
Fatal error: exception File "src/vendor/merlin/src/kernel/mocaml.ml", line 29, characters 2-8: Assertion failed
[...]
```
For this reason I remove all the failing `assert` from the Merlin code, and it happens to work. Maybe I am not calling Merlin correctly, I will see if I can find a way to solve it.

Also thanks for the changes for OCaml 4.10. I am supporting OCaml 4.09 for now as this is the version in use by the Tezos protocol. I made a branch https://github.com/clarus/coq-of-ocaml/tree/ocaml-4.11 to support OCaml 4.11 where the changes are similar to the ones you made. My plan was to make two releases `+4.09` and `+4.11` for each OCaml version.

Indeed `cppo` could be useful. I did not achieve to use it with Merlin in my text editor, so at the time I dropped it in favor of using two branches.

**Comment by clarus** [comment]
By doing these changes:
```diff
@@ -171,6 +171,7 @@ let main () =
     let file_source = Msource.make file_content in
 
     let pipeline = Mpipeline.make merlin_config file_source in
+    Mocaml.with_state (Mocaml.new_state ()) (fun () ->
     let typing = Mpipeline.typer_result pipeline in
     let typedtree = Mtyper.get_typedtree typing in
     let typedtree_errors = Mtyper.get_errors typing in
@@ -190,6 +191,6 @@ let main () =
         !output_file_name
         !json_mode in
     Output.write !json_mode output;
-    exit context output
+    exit context output)
 
 ;;main ()
```
this fixes the `assert` errors. However there is still an issue when running coq-of-ocaml on Tezos specifically (it seems like the environment of variables of each file is empty for Merlin). It seems to me that this appeared with the `v3.4.0` version of Merlin, introducing the package `dot-merlin-reader`. So I am stuck with Merlin `v3.3.9` rather than the latest version for now.

**Comment by avsm** [comment]
cc @trefis @let-def @rgrinberg on this. They probably haven't seen that you're trying to use Merlin in this mode, and we may be able to fix this upstream more easily in Merlin or LSP.

**Comment by clarus** [comment]
Closing the PR as `coq-of-ocaml` is now compatible with OCaml 4.12 *and* uses `ocaml-lsp`, with the work of @lthms . Thanks for the contributions!

**Pull request closed without merging**
