### PR TITLE
Rename TypeIsGadt to AdtParameters

### PR DESCRIPTION
**Pull request by pedrotst**
Since everything is a Gadt it doesn't make sense this module to be named `TypeIsGadt` anymore. Renaming it to AdtParameters allows us to use the translation functions with the regular name `of_ocaml` now, making it more adherent to the rest of the structure of the project.

### CODE REVIEW

**Comment by clarus** [comment]
Ah... so I think the difference with the CI is due to the automatic exit on error in the CI https://stackoverflow.com/questions/2870992/automatic-exit-from-bash-shell-script-on-error Since an exception returns a non-null error code, it stops at the second file I guess.

**Comment by pedrotst** [comment]
Ok, let me know if there is anything I can do about it. I'll keep working on top of these commits.

**Comment by pedrotst** [comment]
Things should work now :)

**Comment by clarus** [comment]
OK cool!

**Comment by clarus** [comment]
I will merge once the tests are done.

**Pull request merged**
